version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/logs
    networks:
      - monitoring
    depends_on:
      - postgres
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/your_db
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=your_user
      - JDBC_PASSWORD=your_password
      - JPA_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - DDL_AUTO=update

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false  # Enable security plugin
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Petar.1524M
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - monitoring

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200  # Use HTTPS for secure connection
      - OPENSEARCH_USERNAME=admin  # Use admin credentials
      - OPENSEARCH_PASSWORD=Petar.1524M  # Set the password for authentication
    networks:
      - monitoring

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    container_name: filebeat
    user: root
    command: >
      bash -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e"
    volumes:
      - ./logs:/logs
      - /var/log:/var/log
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - monitoring
    depends_on:
      - opensearch  # Ensure that Filebeat starts after OpenSearch

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
