apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafbook-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafbook
  template:
    metadata:
      labels:
        app: rafbook
    spec:
      containers:
        - name: rafbook
          image: pstamenic1524m/rafbook:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: rafbook-service
spec:
  type: NodePort
  selector:
    app: rafbook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Exposes your backend to the outside