name: Run Maven and Newman tests and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Step to build Docker image without pushing yet
      - name: Build Docker image
        run: docker build -t pstamenic1524m/rafbook:latest .

      # Step to start backend service and test with Newman
      - name: Start backend service
        run: |
          docker run -d --name backend --network host -p 8080:8080 pstamenic1524m/rafbook:latest

      - name: Run Newman tests
        run: |
          sleep 30 # Wait for the backend to fully start
          docker run --network=host \
            -v ./src/test/IT:/etc/newman \
            postman/newman run /etc/newman/it_service_collection.json --env-var backend_url=http://localhost:8080

      # Step to clean up backend container after tests
      - name: Clean up backend container
        run: |
          docker stop backend
          docker rm backend

      # Only push the Docker image if the tests pass
      - name: Log in to Docker Hub and Push Docker image
        if: success() # Only run if previous steps (including Newman tests) succeed
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push pstamenic1524m/rafbook:latest