name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  setup-java:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  cache:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

  build:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

  jacoco:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

  docker-build:
    runs-on: ubuntu-latest
    needs: jacoco
    steps:
      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build Docker image
        run: docker build -t pstamenic1524m/rafbook:latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push pstamenic1524m/rafbook:latest