name: Run Newman Tests and Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman globally
        run: npm install -g newman

      - name: Install Docker and Docker Compose
        run: |
          # Remove conflicting containerd package
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create Docker Compose file
        run: |
          echo "version: '3.8'
          services:
            app:
              image: pstamenic1524m/rafbook:latest
              ports:
                - '8080:8080'
              pull_policy: always" > docker-compose.yml

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run Newman tests with Docker Compose
        run: |
          docker-compose exec -T app newman run src/test/IT/it_service_collection.json

      - name: Tear down Docker Compose
        run: docker-compose down
