name: Backend API Test with Newman using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Step 3: Generate docker-compose.yml file dynamically
      - name: Create docker-compose.yml
        run: |
          cat <<EOF > docker-compose.yml
          version: '3'
          services:
            backend:
              build: .
              ports:
                - '8080:8080'
              environment:
                - SPRING_PROFILES_ACTIVE=test
            newman:
              image: postman/newman:5.3.2
              command: run /etc/newman/it_service_collection.json --env-var backend_url=http://backend:8080
              depends_on:
                - backend
              volumes:
                - ./src/test/IT:/etc/newman
          EOF

      # Step 4: Run Docker Compose to start services and execute tests
      - name: Run tests with Docker Compose
        run: |
          # Run Docker Compose to start the backend and execute tests with Newman
          docker-compose up --abort-on-container-exit --exit-code-from newman

      # Step 5: Cleanup Docker Compose services
      - name: Cleanup
        run: |
          docker-compose down
