name: Backend API Test with Newman using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 4: Generate docker-compose.yml file
      - name: Create docker-compose.yml
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          services:
            backend:
              image: pstamenic1524m/rafbook:latest
              ports:
                - '8080:8080'
              networks:
                - backend-network
            newman:
              image: postman/newman:latest
              command: run /etc/newman/it_service_collection.json
              depends_on:
                - backend
              volumes:
                - ./src/test/IT:/etc/newman
              networks:
                - backend-network
          networks:
            backend-network:
              driver: bridge
          EOF

      # Step 5: Run Docker Compose to start the backend and execute tests
      - name: Run tests with Docker Compose
        run: |
          docker-compose up --abort-on-container-exit --exit-code-from newman

      # Step 6: Cleanup Docker Compose services
      - name: Cleanup
        run: |
          docker-compose down
