name: Run Integration Tests

on: [push]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Start backend
        run: |
          # Example for starting backend (e.g., via Docker Compose)
          docker-compose -f docker-compose.yml up -d

      - name: Install Newman
        run: npm install -g newman

      - name: Run Integration Tests
        run: newman run src/test/IT/it_service_collection.json
