name: Run Newman Tests and Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g newman
          npm install

      - name: Run Newman tests
        run: newman run src/test/IT/it_service_collection.json

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          echo "version: '3.8'
          services:
            app:
              image: pstamenic1524m/rafbook:latest
              ports:
                - '8080:8080'
              pull_policy: always" > docker-compose.yml
          docker-compose -f docker-compose.yml up -d

      - name: Run tests with Docker Compose
        run: |
          docker-compose exec app newman run src/test/IT/it_service_collection.json

      - name: Tear down Docker Compose
        run: docker-compose down
